---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    micro: resultapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
