---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    micro: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      micro: worker
  template:
    metadata:
      labels:
        micro: worker
    spec:
      containers:
      - name: worker-pod
        image: examplevotingapp_worker:v1